"""Shared phantom geometry — single source of truth for the Isaac Sim scene
and the fluorosim renderer.

Two phantom modes
-----------------
CT mesh (preferred):
    A triangle mesh extracted from the cached CT μ-volume via marching cubes
    (bridge/ct_to_mesh.py).  Vertices are in metres, centred at the volume
    isocenter.  Place at PHANTOM_POS_WORLD_M in Isaac Sim.
    Path: CT_PHANTOM_MESH_OBJ (under output/).

Synthetic ellipsoid (fallback):
    Concentric analytic spheres built directly in USD — used when the CT mesh
    OBJ has not been generated yet.

    shape           = (128, 256, 256)   # (Z, Y, X) voxel order
    spacing_zyx_mm  = (1.0, 0.5, 0.5)
    bone core       = HU 800,  voxel radius 40   (dist function uses voxel indices)
    soft tissue     = HU  40,  voxel radius 60
    air background  = HU -900

    Physical semiaxes in Isaac Sim (X, Y, Z) order:
        soft tissue:  (X=30, Y=30, Z=60) mm
        bone core:    (X=20, Y=20, Z=40) mm

Coordinate convention (fluorosim <-> Isaac Sim):
    fluorosim volume-local axis Z (slow)   <->  Isaac Sim world Z (up)
    fluorosim volume-local axis Y          <->  Isaac Sim world Y
    fluorosim volume-local axis X (fast)   <->  Isaac Sim world X
    fluorosim isocenter                    <->  PHANTOM_POS_WORLD_M
"""

from __future__ import annotations
from pathlib import Path

# ── CT mesh path ──────────────────────────────────────────────────────────────
# Generated by:  python3 bridge/ct_to_mesh.py
# Vertices are in metres, centred at the volume isocenter.
# robot_scene.py uses this mesh when it exists; falls back to the synthetic
# ellipsoids below when it does not.
CT_PHANTOM_MESH_OBJ: Path = (
    Path.home() / "isaac_projects/output/spine_mesh.obj"
)

# ── Phantom isocenter ─────────────────────────────────────────────────────────
# Pose in Isaac Sim world frame (metres / wxyz quaternion).
# Picked so the Franka rest-pose EE at ~(0.43, 0.015, 0.42) m sits inside
# the CT volume bounds (±64 mm from the isocenter).
PHANTOM_POS_WORLD_M: tuple[float, float, float] = (0.43, 0.0, 0.42)
PHANTOM_QUAT_WXYZ: tuple[float, float, float, float] = (1.0, 0.0, 0.0, 0.0)

# Volume-local semiaxes in meters (Isaac Sim X, Y, Z order).
SOFT_TISSUE_SEMIAXES_M: tuple[float, float, float] = (0.030, 0.030, 0.060)
BONE_CORE_SEMIAXES_M: tuple[float, float, float] = (0.020, 0.020, 0.040)

# USD prim paths for the phantom assemblies.
PHANTOM_ROOT_PATH: str = "/World/Phantom"
SOFT_TISSUE_PATH: str = "/World/Phantom/SoftTissue"
BONE_CORE_PATH: str = "/World/Phantom/BoneCore"

# Display colors (linear RGB, 0-1). Light salmon for soft tissue, white for bone.
SOFT_TISSUE_COLOR: tuple[float, float, float] = (0.85, 0.55, 0.50)
BONE_CORE_COLOR: tuple[float, float, float] = (0.95, 0.95, 0.92)
